# TEMA 1: Introduccion a Python

## ¿Que es Python?
 
 Lenguaje de programación ultimamente usado para temas de ciencias de datos, Inteligencia Artificial y Back End.
 
 ## Guia de Estilos Python PEP8

Fuente: https://www.python.org/dev/peps/pep0008/

# Ventajas de Python.

## Tipado dinamico.

Python no necesita que se definan el tipo de variable como se hacen con otros lenguajes de programación, Cuando se inicializa una variable, python le asigna el tipo de Valor.

## Lenguaje Multiparadigma.

Python permite aplicar diferentes paradigmas como Programación orientada a objetos, Java, Programación Imperativa, Programación Funcional.

## Interpretado / Scripts.

Python se puede ejecutar de forma interpretada o usando scripts, por medio de consolas ejecutando instrucciones.

## Extensible.

Python tiene una gran cantidad de modulos y librerias que lo hacen extensible y se pueden ejecutar multiples funcionalidades.

# Pagina principal para instalación de python.

Fuente: https://www.python.org/downloads/

# TEMA 2: Primeros conceptos en python.

## Identificadores

Los Identificadores son nombres que se asignan a elementos y deben cumplir con unas caracteristicas especiales.

1. Pueden combinarce con numeros (09) y letras (A-Z) MAYUSCULAS/minusculas y guion bajo (_).
2. No pueden comenzar por un digito.
3. No pueden usar simbolos especiales (@, !, #, etc).
4. Pueden tener cualquier longitud.

Python distunguemayusculas de minusculas esto quiere decir que identificador e IDENTIFICADOR son 
2 identificadores diferentes.

In [1]:
# Identificadores correctos.
variable = 1
otra_variable = 'Otra'
_mas_variables = [1, 2, 3]
Variable_4 = True

# Identificadores Incorrectos.
@variable = 3
2_variable = 'Esta mal'

SyntaxError: invalid syntax (3721636521.py, line 8)

## Palabras Reservadas,

Python cuenta con varias palabras que son reservada para uso exclusivo de python, por lo tanto no se pueden utilizar.

Algunas Variables.
and, assert, break, class, continue, def, del, elif, else, except, exec, finally, for, from, global, if, import, 
in, is, lambda, not, or, pass, print, raise, return, try, while, with, yield.

In [ ]:
# Comentarios.

# Los comentarios son partes del codigo que el interprete de python no ejecuta, se pueden escribir de varias formas.

# Comentarios de linea para aquellos que solo ucupan 1 linea y se definen con el simbolo # al inicio.

"""
Comentarios en bloque.

para aquellos que ocupen mas de una linea, y se definen por las 3 comillas seguidas
"""

## Sangria.

Python no usa llaves al igual que otros lenguajes de programación para diferenciar los bloques de codigo, Python usa la sangria o identacion del codigo en bloques haciendo una separacion de 4 espacios hacia la derecha siguiendo las recomendaciones de la guia de estilos PEP 8.

In [ ]:
# Ejemplo de Sangria.

variable = 1

if (variable == 1):
    print("Aquí pongo el código a ejecutar.")
    print("Tiene una sangría de 4 espacios.")

## Almacen de Valores.

Son elementos que nos permiten almacenar valores en nuestros programas.

### Variables.
Una variable es un identificador que se le puede asignar un valor para ser retornado en pasos mas adelante.
En python se crea una variable por medio del identificador de asignacion que es el simbolo = 

In [2]:
# Ejemplo de variable:

n = 23
saludo = 'Hola! Qué tal?'
type(n) # Devuelve int
type(saludo) # Devuelve str

str

### Constantes.

Una constante es otra variable con la salvedad que para este tipo de variables, el valor no puede ser modificado.

existen 2 formas de crear constantes 

1. Creando variables en mayuscula
2. Creando un Script de python accesible d dentro del proyecto donde se definen las variables y luego se importan.

In [3]:
# Ejemplo 1 de CONSTANTES

IVA = 0.21
precio = 25
precio_final = precio + (precio * IVA)
print("El precio final es:", precio_final)

El precio final es: 30.25


In [4]:
# Ejemplo 2 de constantes Importamos el fichero de constantes.

import Constantes

precio = 25
precio_final = precio + (precio * Constantes.IVA)
print("El precio final es:", precio_final)

El precio final es: 28.75


## Tipos de Operadores.

En python se pueden definir varios tipos de operadores acorde con la operacion y tipo de datos que se desea trabajar.

### Datos Numericos.

1. Enteros (int): 26, 0b1101 (base binaria), 0x3f4a (base hexadecimal).
2. Flotante (float): 3.14, 5., -67.763
3. Complejos (complex): 0.117j

Con estos tipos de datos se pueden realizar las siguientes operaciones.

In [5]:
# Definiendo valores para operadores aritmeticos. Suma (+)
a = 3.13
b = 6 
suma = a + b
print('Suma: ' + str(suma))

Suma: 9.129999999999999


In [6]:
# Definiendo valores para operadores aritmeticos. # Resta (-)
a = 3.13
b = 6 
resta = a - b
print('Resta: ' + str(resta))

Resta: -2.87


In [7]:
# Definiendo valores para operadores aritmeticos. # Multiplicación (*)
a = 3.13
b = 6 
multiplica = a * b
print('Multiplicación: ' + str(multiplica))

Multiplicación: 18.78


In [8]:
# Definiendo valores para operadores aritmeticos. # Divición (/)
a = 3.13
b = 6 
division = a / b
print('División: ' + str(division))

División: 0.5216666666666666


In [9]:
# Definiendo valores para operadores aritmeticos. # División Entera (//)
a = 3.13
b = 6 
division_entera = a // b
print('División Entera: ' + str(division_entera))

División Entera: 0.0


In [10]:
# Definiendo valores para operadores aritmeticos. # Modulo (%)
a = 3.13
b = 6 
modulo = a % b
print('Modulo: ' + str(modulo))

Modulo: 3.13


In [11]:
# Definiendo valores para operadores aritmeticos. # Exponente (**)
a = 3.13
b = 6 
exponente = a ** b
print('Exponente: ' + str(exponente))

Exponente: 940.2991105042088


### Definiendo valores para operadores asignación.

In [12]:
# Asignacion simple (=)

resultado = 10
print('Asignacion simple (=): ' + str(resultado))

Asignacion simple (=): 10


In [13]:
# Suma y Asignación (+=).
resultado = 10
resultado += 10
print('Suma y Asignación (+=): ' + str(resultado))

Suma y Asignación (+=): 20


In [14]:
# Resta y Asignación (-=).
resultado = 10
resultado -= 10
print('Resta y Asignación (+=): ' + str(resultado))

Resta y Asignación (+=): 0


In [15]:
# Multiplicacion y Asignación (*=)
resultado = 10
resultado *= 10
print('Multiplicacion y Asignación (*=): ' + str(resultado))

Multiplicacion y Asignación (*=): 100


In [16]:
# Division y asignación
resultado = 10
resultado /= 10
print('Division y Asignación (/=): ' + str(resultado))

Division y Asignación (/=): 1.0


In [17]:
# Division Entera y asignación
resultado = 10
resultado //= 10
print('Division Entera y Asignación (//=): ' + str(resultado))

Division Entera y Asignación (//=): 1


In [18]:
# Modulo y asignación
resultado = 14
resultado %= 10
print('Modulo y asignación (%=): ' + str(resultado))

Modulo y asignación (%=): 4


In [19]:
# Exponente y asignación
resultado = 3
resultado **= 2
print('Exponente y asignación (%=): ' + str(resultado))

Exponente y asignación (%=): 9


### Definiendo valores para operadores de Bits

In [20]:
# AND (&): operador lógico and a nivel de bits.
a = 4
b = 5

a & b

4

In [21]:
# OR (|): operador lógico or a nivel de bits.
a = 4
b = 5
a | 5

5

In [22]:
# XOR (^): operador lógico xor a nivel de bits.
a = 4
b = 5

a ^ b

1

In [23]:
# (>>): operador que mueve todos los bits a la derecha
a = 4
b = 5

a >> b

0

### Definiendo valores para operadores de datos Booleanos

In [24]:
# Datos Booleanos AND (and): operador lógico and.
True and False

False

In [25]:
# Datos Booleanos OR (or): operador lógico or.
True or False # Devolverá True 

True

In [26]:
# Datos Booleanos NOT (not): operador de negación lógica.
not True # Devolverá False

False

In [27]:
# Datos Booleanos Igual (==):
5 == 7 # Devolverá False

False

In [28]:
# Datos Booleanos Distinto (!=):
7 != 7 # Devolverá False

False

### Definiendo valores para operadores de cadenas de caracteres

- Son secuencias de caracteres encapsuladas en comillas simples ('Texto') o comillas dobles ("Texto")

In [29]:
mensaje = "Esto es un mensaje de prueba para el curso de Python."

In [30]:
# Retornando pa posición 34
mensaje [34]

'e'

In [31]:
# Retornando un rango de caracteres CADENA[POSICION_INICIAL:POSICION_FINAL]
mensaje[4:15]

' es un mens'

In [32]:
# Retornando desde la posicion Inicial hasta la posicion 20
mensaje [:20]

'Esto es un mensaje d'

In [33]:
# Retornando desde la posicion 40 hasta el final de la cadena de caracteres.
mensaje [40:]

'so de Python.'

In [34]:
# Retornando desde la posicion -10 (es decir 10 desde la derecha).
mensaje [-10:]

'de Python.'

In [35]:
# Retornando desde la posicion inicial hasta la posicion -10 (es decir 10 desde la derecha).
mensaje [:-10]

'Esto es un mensaje de prueba para el curso '

In [36]:
# Concatenar: Retorna una cadena de caracteres uniendo los caracteres de dos cadenas.
"Hola " + "Mundo"

'Hola Mundo'

In [37]:
# Multiplicar: repite la cadena tantas veces como se indica.
"Hola Mundo!!" * 3

'Hola Mundo!!Hola Mundo!!Hola Mundo!!'

In [38]:
# LEN(): Permite obtener la longitud de la cadena.
len(mensaje)

53

In [39]:
# FIND(): Obtiene la primera posición de la sub cadena que se pasa por parametro
mensaje.find('Python')

46

In [40]:
# UPPER(): Convierte los caracteres en mayuscula.
mensaje.upper()

'ESTO ES UN MENSAJE DE PRUEBA PARA EL CURSO DE PYTHON.'

In [41]:
# LOWER(): Convierte los caracteres en minuscula.
mensaje.lower()

'esto es un mensaje de prueba para el curso de python.'

In [42]:
#REPLACE(): permite modificar el contenido de la cadena ("Valor a remplazar", "Valor Nuevo")
mensaje.replace("curso", "seminario")

'Esto es un mensaje de prueba para el seminario de Python.'

In [43]:
# Tipo NONE: se usa para definir el valor de una variable como nada o ninguna cosa
variable = None
type(variable)

NoneType

### Transformación de tipos de datos.

In [44]:
# Convertir a cadena de caracteres (str): Convierte el objeto que se pasa por parametro a cadena de caracteres
valor = 10
str(valor)

'10'

In [45]:
# Convertir a valor entero (int): Convierte el objeto que se pasa por parametro a entero
valor1 = "21"
int(valor1)

21

In [46]:
# Convertir a valor flotante (float): Convierte el objeto que se pasa por parametro a flotante
valor2 = 30
float(valor2)

30.0

In [47]:
# Convertir a valor complejo (complex): Convierte el objeto que se pasa por parametro a complex
valor3 = 10.78
complex(valor3)

(10.78+0j)

In [48]:
# Convertir a valor booleano (bool): Convierte el objeto que se pasa por parametro a booleano TRUE or FALSE
valor4 = 10.78
bool(valor4)

True

In [49]:
valor5 = False
bool(valor5)

False

In [50]:
valor6 = 0
bool(valor6)

False

# TEMA 3. Programación Basica.

## Listas:

- Son estructuras de datos con objetos de datos separados por coma (,)
- Son MUTABLES: Se puede cambiar el valor la lista (Cambiar el orden de los elementos, eliminar elementos).
- Pueden contener elementos de diferente tipos o estructuras.
- Se declaran entre corchetes ([objeto1,objeto2,objetoN])

In [51]:
lista = [5, 'Hola Mundo', True]
print(lista)

[5, 'Hola Mundo', True]


In [52]:
# Para acceder a la posicion de una lista se le pasa el indice del elemento. El primer elemento de la lista es 0
lista = [5, 'Hola Mundo', True]
lista[1]

'Hola Mundo'

In [53]:
# (:) Rango de Indices: Permite acceder a un conjunto de elementos de una lista.
l_dias_semana = ['Lunes','Martes','Miercoles','Jueves','Viernes','Sabado','Domingo']
l_dias_semana[:2]

['Lunes', 'Martes']

In [54]:
l_dias_semana = ['Lunes','Martes','Miercoles','Jueves','Viernes','Sabado','Domingo']
l_dias_semana[3:]

['Jueves', 'Viernes', 'Sabado', 'Domingo']

In [55]:
# Cuando se usan valores Negativos (-) python devuelve los elementos a partir de la posicion de la derecha
l_dias_semana = ['Lunes','Martes','Miercoles','Jueves','Viernes','Sabado','Domingo']
l_dias_semana[-2]

'Sabado'

## Funciones aplicables a las listas.

In [56]:
# LEN: Retorna la longitud de una lista
l_dias_semana = ['Lunes','Martes','Miercoles','Jueves','Viernes','Sabado','Domingo']
len(l_dias_semana)

7

In [57]:
# INDEX: Retorna la posicion que ocupa un elemento de la lista
l_dias_semana = ['Lunes','Martes','Miercoles','Jueves','Viernes','Sabado','Domingo']
l_dias_semana.index('Jueves')

3

In [58]:
# INSERT: Inserta un elemento de la lista en la posición que se le indica. INSERT (POSICIÓN, OBJETO)
l_dias_semana = ['Lunes','Martes','Miercoles','Jueves','Viernes','Sabado','Domingo']
l_dias_semana.insert(7, 'Festivos')
l_dias_semana

['Lunes',
 'Martes',
 'Miercoles',
 'Jueves',
 'Viernes',
 'Sabado',
 'Domingo',
 'Festivos']

In [59]:
# APPEND: Inserta un elemento al final de la lista.
l_numeros = [1,2,3,4,5,6,7,8]
l_numeros.append([9,10])
l_numeros

[1, 2, 3, 4, 5, 6, 7, 8, [9, 10]]

In [60]:
# EXTEND: agrega un elemento o conjunto de elementos a la lista.
l_numeros = [1,2,3,4,5,6,7,8]
l_numeros.extend([9,10])
l_numeros

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [61]:
# REMOVE: elimina el elemento que se pasa por parametro de la lista.
l_dias_semana = ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo', 'Festivos']
l_dias_semana.remove('Festivos')
l_dias_semana

['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']

In [62]:
# COUNT: Retorna el numero de veces que se encuentra un elemento en la lista
l_dias_semana = ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo', 'Viernes']
l_dias_semana.count('Viernes')

2

In [63]:
# REVERSE: invierte la posición de todos los elementos de una lista
l_dias_semana = ['Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo']
l_dias_semana.reverse()
l_dias_semana

['Domingo', 'Sabado', 'Viernes', 'Jueves', 'Miercoles', 'Martes', 'Lunes']

In [64]:
# SORT: ordena los elementos de una lista
lista = [1,5,9,7,6,3,2,8,4]
lista.sort()
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [65]:
# SORT(reverse=TRUE): ordena los elementos de una lista en sentido inverso al inicial
lista = [1,5,9,7,6,3,2,8,4]
lista.sort(reverse=True)
lista

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [66]:
#POP: Elimina y devuelve el elemento que se encuentra en la posicion que se pasa por parametro.
lista = [1,5,9,7,6,3,2,8,4]
lista.pop(1)

5

## Tuplas:

- Son un conjunto de elemnetos separado por coma (,).
- Son INMUTABLES No se pueden modificar una vez creadas.
- Para acceder a los elelmentos de la tupla se hace igual que las listas TUPLA [INDICE]

In [67]:
tupla = 'Hola Mundo', 3.4, True, 'Hola'
tupla

('Hola Mundo', 3.4, True, 'Hola')

In [68]:
# Accediendo a los elementos de la tupla
tupla = 'Hola Mundo', 3.4, True, 'Hola'
tupla[1]

3.4

## Funciones aplicables a las Tuplas.

In [69]:
# LEN: Metodo que retorna la longitud de la tupla
tupla_dias_semana = 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo'
len(tupla_dias_semana)

7

In [70]:
# COUNT: Numero de veces que se encuentra un elemento en la tupla.
tupla_dias_semana = 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo', 'Viernes'
tupla_dias_semana.count('Viernes')

2

In [71]:
# INDEX: Retorna la posicion que ocupa el lemento.
tupla_dias_semana = 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo'
tupla_dias_semana.index('Sabado')

5

## Diccionarios.

- Son una estructura de datos definido como conjunto de pares clave:valor
- Claves(keys) son unics y estan en lugar de indices 
- Se accede a travez de su clave.
- Se crean por medio de llaves {}

In [72]:
# Creando diccionario dias de la semana
diccionario_dias_semana = {
    '01':'Lunes',
    '02':'Martes',
    '03':'Miercoles',
    '04':'Jueves',
    '05':'Viernes',
    '06':'Sabado',
    '07':'Domingo'}

diccionario_dias_semana

{'01': 'Lunes',
 '02': 'Martes',
 '03': 'Miercoles',
 '04': 'Jueves',
 '05': 'Viernes',
 '06': 'Sabado',
 '07': 'Domingo'}

In [73]:
# Para acceder a uno de los valores es necesario conocer la clave y se accede en corchetes.
diccionario_dias_semana['05']

'Viernes'

In [74]:
# Creando nuevo elemento en el diccionario.
diccionario_dias_semana['08'] = 'Festivos'
diccionario_dias_semana

{'01': 'Lunes',
 '02': 'Martes',
 '03': 'Miercoles',
 '04': 'Jueves',
 '05': 'Viernes',
 '06': 'Sabado',
 '07': 'Domingo',
 '08': 'Festivos'}

In [75]:
# DICT(): Me permite crear un diccionario nuevo sin ningun elemento.

diccionario_vacio = dict()
type(diccionario_vacio)

dict

## Funciones aplicables a los Diccionarios.

In [76]:
# LIST: devuelve una lista de todas las claves incluidas en un diccionario
diccionario_dias_semana = {
    '01':'Lunes',
    '02':'Martes',
    '03':'Miercoles',
    '04':'Jueves',
    '05':'Viernes',
    '06':'Sabado',
    '07':'Domingo'}

list(diccionario_dias_semana)

['01', '02', '03', '04', '05', '06', '07']

In [77]:
# SORTED: Ordena la lista del diccionario.
sorted(diccionario_dias_semana)

['01', '02', '03', '04', '05', '06', '07']

In [78]:
# IN: Comprueba si una clave se encuentra en el diccionario.
'08' in diccionario_dias_semana

False

In [79]:
# DEL: Elimina un elemento del diccionario.
diccionario_dias_semana = {
    '01': 'Lunes',
    '02': 'Martes',
    '03': 'Miercoles',
    '04': 'Jueves',
    '05': 'Viernes',
    '06': 'Sabado',
    '07': 'Domingo',
    '08': 'Festivos'}
del diccionario_dias_semana['08']
diccionario_dias_semana

{'01': 'Lunes',
 '02': 'Martes',
 '03': 'Miercoles',
 '04': 'Jueves',
 '05': 'Viernes',
 '06': 'Sabado',
 '07': 'Domingo'}

## Conjuntos.

- Son colecciones NO ordenadas de elementos.
- No contienen repetición de elementos.
- Se crean los conjuntos por elementos separados por coma (,) y delimitados por llaves {}
- No se puede acceder a los elementos a traves del indice dado que no son de tipo lista ordenada.

In [80]:
# Creando un conjunto de marcas de carros.
conjunto_carros = {'audi', 'mercedes', 'seat', 'ferrari', 'ferrari', 'renault'}
conjunto_carros

{'audi', 'ferrari', 'mercedes', 'renault', 'seat'}

In [81]:
# SET: Funcion que permite crear un conjunto vacio
conjunto_vacio = set()

## Funciones aplicables a los Conjuntos.

In [82]:
# UNION: Operación matematica que retorna la union de dos conjuntos.
conjunto1 = {1,2,3}
conjunto2 = {3,4,5}
conjunto1.union(conjunto2)

{1, 2, 3, 4, 5}

In [83]:
# INTERSECTION: operación matematica para obtener la interseccion de 2 conjuntos.
conjunto1 = {1,2,3}
conjunto2 = {3,4,5}
conjunto1.intersection(conjunto2)

{3}

In [84]:
# DIFERENCE: Se obtiene la diferencia de 2 conjuntos.
conjunto1 = {1,2,3}
conjunto2 = {3,4,5}
conjunto1.difference(conjunto2)

{1, 2}

In [85]:
# IN: Comprueba si un elemento se encuentra dentro del conjunto.
conjunto1 = {1,2,3,4,5,6,7}
3 in conjunto1

True

In [86]:
# LEN: retorna la longitud del conjunto.
conjunto1 = {1,2,3,4,5,6,7}
len(conjunto1)

7

## Ejecuciones condicionales.

In [87]:
## Expresión if: Ejecuta un bloque de instrucciones solo si la expresion logica es TRUE.
"""
if (EXPRESION_LOGICA):
 sentencia_1
 sentencia_2
"""
print("Escribe un numero de 1 a 10")
number = int(input())
if(number > 5 ):
    print("!Soy mayor de 5")

Escribe un numero de 1 a 10
8
!Soy mayor de 5


In [88]:
# Expresion ELSE: Se ejecuta cuando el bloque IF no cumple con la condicion TRUE.
"""
if (EXPRESION_LOGICA):
 sentencia_1
 sentencia_2
 ...
else:
 sentencia_1
 sentencia_2
 ...
"""
print("Escribe un número de 1 a 10")
number = int(input())
if (number > 5):
 print("¡Soy mayor que 5!")
else:
 print("Soy menor o igual que 5")

Escribe un número de 1 a 10
4
Soy menor o igual que 5


In [89]:
# Expresion ELIF: permite validar mas condiones dentro de un IF.
"""
if (EXPRESION_LOGICA):
 sentencia_1
 ...
elif (EXPRESION_LOGICA_2):
 sentencia_1
 ...
elif (EXPRESION_LOGICA_3):
 sentencia_1
 ...
...
else:
 sentencia_1
 sentencia_2
 ...
"""
print("Escribe un número de 1 a 10")
number = int(input())
if (number > 5):
 print("¡Soy mayor que 5!")
elif (number == 5):
 print("Soy el número 5")
else:
 print("Soy menor o igual que 5")

Escribe un número de 1 a 10
6
¡Soy mayor que 5!


## Ejecuciones Iterativas

In [149]:
# BUCLE WHILE: repite un bloque de codigo mientras se cumpla una condición definida y su retorno sea FALSE.
"""
while (EXPRESION_LOGICA):
 sentencia_1
 sentencia_2
"""

# Imprimir secuencia de numeros desde el numero 10 hasta el numero 0
numero = 10
fin = 0
while(numero > fin):
    numero -=1
    print(numero)

9
8
7
6
5
4
3
2
1
0


In [150]:
# BUCLE FOR: recorre un conjunto de elementos en cualquier sentido
"""
for VARIABLE in OBJETO:
 sentencia_1
 sentencia_2
"""
numeros = [5,4,3,2,1,0]
for numero in numeros:
    print(numero)
else:
    print("Fin del recorrido")

5
4
3
2
1
0
Fin del recorrido


In [151]:
cadena = "Hola Mundo"
for i in range(0,len(cadena),1):
    print(cadena[i])

H
o
l
a
 
M
u
n
d
o


In [152]:
#BREAK: es una sentencia que permite romper el ciclo.
numeros = list(range(10))
for n in numeros:
    if (n == 5):
        print("Rompe el bucle")
        break
    print(n)

0
1
2
3
4
Rompe el bucle


In [153]:
#CONTINUE: Es otra sentencia que permite saltar una iteración del bucle sin romper todo el ciclo.
numeros = list(range(10))
for n in numeros:
    if (n == 5):
        print("Saltando la vuelta 5")
        continue
    print(n)

0
1
2
3
4
Saltando la vuelta 5
6
7
8
9


In [154]:
#ITERADORES: es un objeto que oermite iterar sobre otro para obtener el siguiente elemento iter(objeto) 
#para consultar el objetonext()
cadena = "Hola"
iterador = iter(cadena)
next(iterador)
next(iterador)
next(iterador)
next(iterador)

'a'

## Definición de Funciones

- Permiten encapsular un bloque de instrucciones que pueden ser reutilizados.

In [155]:
"""
def NOMBRE_FUNCION(ARG1, ARG2,...):
    sentencia_1
    sentencia_2
    ...
    return OBJETO_DEVOLVER
"""
def area_triangulo(base, altura):
    area = (base * altura) / 2
    return area

# Invocando la funcion pasando argumentos
area_triangulo(6, 5)

15.0

### Parametros y Argumentos

- Los parametros son los valores que se definen en una función
- Los argumentos son los valores que se introducen en una función

In [97]:
# Argumentos por posición: Se envian en el mismo orden en que se definen los parametros
area_triangulo(6, 5)

15.0

In [98]:
# Arumentos por nombre: Se envian utilizando los nombres de los parametros.
area_triangulo(base= 10, altura=5)

25.0

## Parametros Indeterminados

- Se usan en los casos que es necesario pasar parametros indeterminados en las funciones.

In [99]:
"""
Arguentos por posición: se definen los parametros como lista dinamica, se incluye un (*) antes del nombre del
parametro
"""
def imprime_numeros(*args):
    for numero in args:
        print(numero)
        
#Invocando la función
imprime_numeros(1,7,89,46,9394)

1
7
89
46
9394


In [100]:
"""
Argumentos por Nombre: se definen los parametros como un diccionario dinamico se incluye dos (**) antes del 
nombre del parametro 
"""
def imprime_valores(**args):
    for argumento in args:
        print(argumento, '=>', args[argumento])

# Invocando la función
imprime_valores(arg1='Hola', arg2=[2,3,4], arg3=876.98)

arg1 => Hola
arg2 => [2, 3, 4]
arg3 => 876.98


## Documentar funciones.

- Para documentar las funciones se utilizan los docstring, se debe incluir un comentario despues de la cabecera de la función.

In [101]:
# Documentando una función.
def potencia(base, exponente):
    """
    Función que calcula la potencia de dos números.
     
    Argumentos:
    base ‐‐ base de la operación.
    exponente ‐‐ exponente de la operación.
    """
    return base ** exponente

In [102]:
# Invocando la ayuda de la función documentada.
help(potencia)

Help on function potencia in module __main__:

potencia(base, exponente)
    Función que calcula la potencia de dos números.
     
    Argumentos:
    base ‐‐ base de la operación.
    exponente ‐‐ exponente de la operación.



## Funciones incluidas en python

- Modulo math: Modulo matematico que incluye funciones matematicas. (math)
- Modulo aritmetico: para realizar operaciones aritmeticas => fabs(x), gcd(x,y), floor(x), ceil(x), factorial(x)
- Modulo trigonometria: Para realizar calculos trigonometricos => sin(x), cos(x), tan(x), asin(x), acos(x)
- Modulo sys: proporciona variables y metodos relacionados con el interprete de python.
    - argv(): retorna lista con todos los argumentos pasados por linea de comandos
    - executable(): retorna la ruta absoluta del fichero
    - platform(): retorna la plataforma sobre la que se esta ejecutando.
    - getdefaultenconding(): Retorna el sistema de codificación por defecto del sistema.
- Modulo os: proporciona acceso a variables y funciones que interacturan con el sistema operativo.
    - os.getcwd(): Retorna la ruta del directorio actual.
    - os.mkdir(path): Crea una carpeta
    - os.rename(name1, name2): Renombra un fichero
    - ...... y muchos mas.
- Modulo random: proporciona metodos para obtener valores aleatorios.
    - randint(x, y): Retorna un numero aleatorio entre x e y
    - choise(secuencia): retorna dato aleatorio de los datos de una secuencia.   

## Funciones Anonimas.

- Son funciones que no se les asigna identificador def NOMBRE_FUNCION estas funciones no incluyen un bloque solo tienen una unica expresión.
- Para implementarlas se usa la expresión LAMBDA

In [103]:
# Función normal que recibe un numero y retorna el valor al cuadrado.
def cuadrado(x):
    resultado = x ** 2
    return resultado

# Invocando la función
cuadrado(5)

25

In [104]:
# Convirtiendo función normal en función lambda {lambda parámetro_1, parámetro_2: expresión}
cuadrado = lambda x: x ** 2

# Invocando la función
cuadrado(8)

64

## Aplicando filter() map() con funciones lambda

- filter(): Permmite filtrar elementos de una secuencia so se cumple la función condicional filter(funcion,objeto).
- map(): permite aplicar una función a todos los elementos de una secuencia. map(funcion, objeto).

In [105]:
# Filter:
# Definiendo lista de numeros para analizar.
lista = [1,2,3,4,5,6,7,8,9,10]

In [106]:
# Definición de expresion landa que analiza si un numero es par o no
es_par = lambda numero: numero % 2 == 0

In [107]:
# Aplicando filtro para obtener los numeros pares, se debe insertar en una lista.
list(filter(es_par, lista))

[2, 4, 6, 8, 10]

In [108]:
# Map:
# Definiendo lista de numeros para analizar.
lista = [1,2,3,4,5,6,7,8,9,10]

In [109]:
# Definición de expresion landa que saca el cuadrado del numero
cuadrado = lambda x: x ** 2

In [110]:
# Aplicando filtro para obtener numeros pares.
list(map(cuadrado, lista))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

## Modulos y paquetes

- Los modulos son los ficheros .py que se crean para un proyecto tienen variables y funciones
- Un paquete es una carpeta que contiene varios modulos, importante los paquetes contienen lo siguiente.
    - Un fichero llamado __init__.py que incluye los import
- Ejemplo de un paquete.

        paquete/
        ├── __init__.py
        ├── modulo1.py
        └── modulo2.py

In [111]:
# Creacion de un modulo.
"""
1. Crear un fichero con extencion .py
2. Agregar las funciones al fichero.
3. Almacenarlo en una carpeta.
4. importarlo con la funcion import fichero.yml
"""
import figuras as fig

fig.circunferencia.perimetro(5)

31.41592653589793

In [112]:
# Simplificando las importaciones con la palabra reservada FROM
from figuras import circunferencia as circ
from figuras import poligono as pol

circ.perimetro(15)

94.24777960769379

In [113]:
#Documentando los modulos: Se puede usar las comillas """ docstring """ al iniciar el modulo.
#Invocando la ayuda del modulo.
from figuras import circunferencia
help(circunferencia)

Help on module figuras.circunferencia in figuras:

NAME
    figuras.circunferencia

DESCRIPTION
    Modulo circunferencia:
    Incluye las funciones que nos permiten obtener el perímetro o
    área de una circunferencia.

FUNCTIONS
    area(radio)
    
    perimetro(radio)

FILE
    /opt/notebooks/IntroduccionPython/figuras/circunferencia.py




In [114]:
#Documentando los paquetes: Se puede usar las comillas """ docstring """ al iniciar el archivo __init__.py .
#Invocando la ayuda del modulo.
import figuras
help(figuras)

Help on package figuras:

NAME
    figuras

DESCRIPTION
    paquetes:
    Incluye los paquetes.
    - circunferencia
    - poligono

PACKAGE CONTENTS
    circunferencia
    poligono

FILE
    /opt/notebooks/IntroduccionPython/figuras/__init__.py




## Programación Orientada a Objetos.

- Ub objeto es una abstracción de los datos con las caracteristicas.
    - Tiene un Estado: El objeto tiene un valor concreto en un momento determinado.
    - Tiene un comportamiento: A partir de un conjunto de metodos se puede modificar el estado del objeto.
    - Tiene una identidad: Tienen un identificador que eprmite identificar al objeto en forma unica.

In [115]:
# Definiendo una clase como un objeto que tiene caracteristicas de comportamiento e identidad
class Libro:
    titulo = 'Don Quijote de la Mancha'
    autor = 'Miguel de Cervantes'
    isbn = '0987-7489'
    editorial = 'Mi Editorial'
    paginas = 934
    edicion = 34

In [116]:
# Creando un objeto dee la clase Libro.
mi_libro = Libro()

In [117]:
# Consultando una caracteristica del nuevo objeto mi_libro creado a partir de la clase Libro.
mi_libro.titulo

'Don Quijote de la Mancha'

In [118]:
# Metodos: Son las funciones que definen que operaciones se puede realizar sobre los objetos
class Libro:
    titulo = 'Don Quijote de la Mancha'
    autor = 'Miguel de Cervantes'
    isbn = '0987-7489'
    editorial = 'Mi Editorial'
    paginas = 934
    edicion = 34
    
    def imprime(self):
        print(self.titulo + " - " + self.autor)

In [119]:
# Obteniendo el metodo imprime.

# Creando un objeto dee la clase Libro.
mi_libro = Libro()

mi_libro.imprime()

Don Quijote de la Mancha - Miguel de Cervantes


## Expresiones Regulares.

- Es una secuencia de caracteres que perminten definir patrones de texto.
- Se usa importando el modulo re.

In [120]:
# Importando modulo re para usar los metods que permiten realizar expresiones regurales.
import re

In [121]:
# SEARCH(): Metodo para buscar la primera aparicion del patrón en la cadena de texto
# Retorna un objeto tipo match para obtener las posiciones 
mensaje = "Esto es un mensaje de prueba para el curso de Python."
match = re.search('curso', mensaje)
print ("Comienzo ", match.start(), "Final ", match.end())

Comienzo  37 Final  42


In [122]:
# MATCH(): Busca un patron al principio de la cadena, en caso e no existir returna un objeto tipo NONE
mensaje = "Esto es un mensaje de prueba para el curso de Python."
match = re.match('Esto', mensaje)
print("Comienzo ",  match.start(), "Final", match.end())

Comienzo  0 Final 4


In [123]:
# SPLIT(): Metodo que permite dividir una cadena de caracteres siguiendo un patron.
mensaje = "Esto es un mensaje de prueba para el curso de Python."
re.split(' ', mensaje)

['Esto',
 'es',
 'un',
 'mensaje',
 'de',
 'prueba',
 'para',
 'el',
 'curso',
 'de',
 'Python.']

In [124]:
# SUB(): permite sustituir patrones encontrados por otra subcadena pasada por aprametro.
mensaje = "Esto es un mensaje de prueba para el curso de Python."
re.sub('Python', 'Java', mensaje)

'Esto es un mensaje de prueba para el curso de Java.'

In [125]:
# FINDALL(): busca todas las apariciones de un patrón dentro de una cadena de caracteres. 
# Retorna una lista con todas las subcadenas
mensaje = "Esto es un mensaje de prueba para el curso de Python."
re.findall('de', mensaje)

['de', 'de']

In [126]:
# Texto con un grado de complejidad mas amplio, extraido de wikipedia
texto = "Un texto es una composición de signos codificados en un sistema de escritura que forma una unidad de\n sentido. También es una composición de caracteres imprimibles (con grafema) generados por un algoritmo de \n cifrado que, aunque no tiene sentido para cualquier persona, sí puede ser descifrado por su destinatario \n original. En otras palabras, un texto es un entramado de signos con una intención comunicativa que adquiere \n sentido en determinado contexto."

In [127]:
# CARACTERES DE ESCAPE:
"""
Utilizados para definir caracteres especiales dentro de una cadena de texto.
- Comienzan con una barra invertida (\)
- \n: salto de línea.
- \t: tabulador.
- \\: barra diagonal inversa.
- \d: un dígito.
- \w: un carácter alfanumérico.
- \s: un espacio en blanco.
- \D: carácter que no sea un dígito.
- \W: carácter que no sea alfanumérico.
"""


'\nUtilizados para definir caracteres especiales dentro de una cadena de texto.\n- Comienzan con una barra invertida (\\)\n- \n: salto de línea.\n- \t: tabulador.\n- \\: barra diagonal inversa.\n- \\d: un dígito.\n- \\w: un carácter alfanumérico.\n- \\s: un espacio en blanco.\n- \\D: carácter que no sea un dígito.\n- \\W: carácter que no sea alfanumérico.\n'

In [128]:
# Ejemplo 1: Sustituyendo los saltos de linea por el texto ** AQUI **

# Importando modulo re para usar los metods que permiten realizar expresiones regurales.
import re

texto2 = re.sub('\n', '**AQUI**', texto)
print (texto2)

Un texto es una composición de signos codificados en un sistema de escritura que forma una unidad de**AQUI** sentido. También es una composición de caracteres imprimibles (con grafema) generados por un algoritmo de **AQUI** cifrado que, aunque no tiene sentido para cualquier persona, sí puede ser descifrado por su destinatario **AQUI** original. En otras palabras, un texto es un entramado de signos con una intención comunicativa que adquiere **AQUI** sentido en determinado contexto.


In [129]:
# GRUPOS DE CARACTERES. Permite encontrar un patron y capturar el resultado para procesar mas adelante.

# Ejemplo 2: capturar las palabras que inicien por se- y continuen con otra palabra

pattern = 'se\w+\s\w+'
texto3 = re.findall(pattern,texto)
print (texto3)

['sentido para', 'ser descifrado', 'sentido en']


In [130]:
# Ejemplo 2: Agrupando la palabra que empiea por se- unicamente.
pattern = '(se\w+)\s\w+'
texto4 = re.findall(pattern, texto)
print (texto4)

['sentido', 'ser', 'sentido']


In [131]:
# METACARACTERES: Son caracteres que tienen significado especial en las expresiones regulares.
## |: permite separar alternativas buscando dentro de un texto

## Ejemplo 3: sustituir cualquier aparición de las palabras es o ser por **AQUI**

pattern = 'es|ser'
texto5 = re.sub(pattern, '**AQUI**', texto)
print(texto5)

Un texto **AQUI** una composición de signos codificados en un sistema de **AQUI**critura que forma una unidad de
 sentido. También **AQUI** una composición de caracter**AQUI** imprimibl**AQUI** (con grafema) generados por un algoritmo de 
 cifrado que, aunque no tiene sentido para cualquier persona, sí puede **AQUI** d**AQUI**cifrado por su d**AQUI**tinatario 
 original. En otras palabras, un texto **AQUI** un entramado de signos con una intención comunicativa que adquiere 
 sentido en determinado contexto.


In [132]:
## ?: El elemento que precede aparece una vez o ninguna.
## Ejemplo 4: buscando cualquier numero que tenga un digito o ninguno seguido de un espacio.

ejemplo = '1 22 33 4444 55555 666666 7777777 88888888 999999999'
pattern = '\d?\s'
texto6 = re.findall(pattern, ejemplo)
print(texto6)

['1 ', '2 ', '3 ', '4 ', '5 ', '6 ', '7 ', '8 ']


In [133]:
## +: El elemento que lo precede aparece una o mas veces.
## buscar el numero donde aparece el digito 3 una o mas veces.

ejemplo = '1 22 33 4444 55555 666666 7777777 88888888 999999999'
pattern = '3+'
texto7 = re.findall(pattern, ejemplo)
print(texto7)

['33']


In [134]:
## *: El elemento que lo precede aparece ninguna o mas veces.
## buscar que parte contiene el digito 1 ninguna o mas veces seguido del numero 2
ejemplo = '12233444455555666666777277788888888999999999'
pattern = '(1*2)'
texto8 = re.findall(pattern, ejemplo)
print(texto8)

['12', '2', '2']


In [135]:
## {n}: El elemento que precede aparece n veces.
## buscar que parte de la cadena de caracteres tiene exactamente 3 digitos.
ejemplo = '1 22 333 4444 55 66666'
pattern = '\d{3}'
texto9 = re.findall(pattern, ejemplo)
print(texto9)

['333', '444', '666']


In [136]:
## {n,m}: El elemento anterior aparece entre n y m si n esta vacio elemento aparece 0 veces. 
##        Si m es vacio el elemento aparece n o mas veces.
## buscar que parte de la cadena de texto tiene 2 o 3 digitos seguidos.
ejemplo = '1 22 333 4444 55 66655566'
pattern = '[2,5]{2,3}'
texto10 = re.findall(pattern, ejemplo)
print(texto10)

['22', '55', '555']


In [137]:
## []: Busca cadenas que tengan algunos de los caracteres definidos dentro de los corchetes.
## buscar que parte de la cadena tiene los digitos 2 o 3 repetidos entre 2 y 3 veces.
ejemplo = '1 22 333 4444 55 66655566'
pattern = '[2,3]{2,3}'
texto11 = re.findall(pattern, ejemplo)
print(texto11)

['22', '333']


In [138]:
## -: Permite definir un rango de caracteres
## buscar que parte de la cadena tiene los valores entre 1 y 3 repetidos 2 o mas veces.
ejemplo = '1 22 333 4444 55 66655566'
pattern = '[1-3]{2,}'
texto11 = re.findall(pattern, ejemplo)
print(texto11)

['22', '333']


## Excepciones.

- Es un bloque de codigo que se ejecutara cuando se detecte un error.
- Es necesario el uso de los bloques try - except para controlar las excepciones.

In [139]:
# Ejemplo de bloque de excepciones Accediendo a una posición que no existe.
lista = [2,3,4]
try:
    print(lista[4])
except:
    print("No existe posición")
print("Continua Ejecución")

No existe posición
Continua Ejecución


In [140]:
# Ejemplo creando diferentes tipos de excepciones.
lista = [2,3,4]
try:
    print(lista[5])
except IndexError:
    print("No existe posición")
except TypeError:
    print("El tipo de la operación es erróneo")
except:
    print("Ha ocurrido un error")
    
print("Finaliza el ciclo")

No existe posición
Finaliza el ciclo


## excepciones con bloque else.

- Se crea un bloque else para controlar las ejecuciones que no tienen errores.

In [141]:
# Ejemplo creando una excepción con un bloque else.
lista = [2, 3, 4]
try:
    print(lista[2])
except:
    print("No existe esa posición")
else:
    print("Está perfecto")
print("Sigo con la ejecución")

4
Está perfecto
Sigo con la ejecución


## Bloque finally.

- Se ejecuta siempre y cuando haya habido o no un error en el bloque try.
- La estructura completa es try-except-finally

In [142]:
# Ejemplo creando una excepción con bloque finally.
lista = [2, 3, 4]
try:
    print(lista[2])
except:
    print("No existe esa posición")
else:
    print("Está perfecto")
finally:
    print("Hemos terminado el bloque try-except")
print("Sigo con la ejecución")

4
Está perfecto
Hemos terminado el bloque try-except
Sigo con la ejecución


# Lanzar errores.

- Es una opción para generar los propios errores que se puedan gestionar en otro lado del programa.
- Se crean con la sentencia raise seguido del tipo de error y el mensaje.

In [143]:
# Ejemplo creando un error propio con raise.
try:
    raise TypeError("Este es un ejemplo de error personalizado")
except:
    print("He detectado error")

He detectado error


## Compresión de Listas.

- Permite crear listas donde cada uno de los miembros de la lista es el resultado de una operación.
- [OPERACIÓN for ITEM in SECUENCIA ]
- [OPERACIÓN for ITEM in SECUENCIA if CONDICIÓN ]

In [144]:
# Ejemplo compresion de listas.
# crear una lista que almacene { el resultado de aplicar el cuadrado a los numeros de 1 a 10 }
result = [ i **2 for i in range(1,11)]
print(result)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [145]:
# Ejemplo de compresion de lista con condional
# [ operacion FOR item IN secuencia IF condición ]
result = [ i**2 for i in range (1,11) if i%3 == 0 ]
print(result)

[9, 36, 81]


## Compresión de listas aplicada a los Diccionarios.

- La compresión de listas se puede aplicar a otro tipo de colecciones como son los diccionarios.
- Es necesario definir la clave y el valor de cada elemento
- { clave: valor FOR item IN secuencia IF condición }

In [146]:
# ejemplo con diccionarios: 
"""
Crear un diccionario que almacene el resultado de aplicar el cuadrado a los nros pares entre 1 y 10 donde la 
clave del resultado sea el numero con el que se calcula el cuadrado.
"""
result = { i: i**2 for i in range(1,11) if i%2==0 }
print(result)

{2: 4, 4: 16, 6: 36, 8: 64, 10: 100}


## Compresión de listas aplicada a los conjuntos.

- Se puede adaptar la expresión para que funcione de la misma forma que los diccionarios.
- Se usan los simbolos de creación de conjuntos seguido de la misma estructura de comprensión.
- { item FOR item IN secuencia IF condición }

In [147]:
# Ejemplo de Conjuntos.
"""
crear una secuencia que almacena el resultado de aplicar el cuadrado a los numeros pares que hay de 1 a 10
"""
result = { i**2 for i in range(1,11) if i%2==0 }
print(result)

{64, 100, 4, 36, 16}


## Numpy

- Es un modulo rientado a las librerias cientificas, proporciona nuevas estructuras de datos como matrices, matrices multidimencionales etc.
- Es una libreria que forma parte de la base del analisis de datos.

In [2]:
# Importando NUMPY
import numpy as np

In [3]:
# Arrays en numpy
# Son una secuencia de valores que tienen asignada una posición, mas rapidos que las listas de python.
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [4]:
# Accediendo a una posición del array.
array[2]

3

In [5]:
# Accediendo elementos al array de diferente tipo.
array = np.array([1.0, 'Hola', True])
array

array(['1.0', 'Hola', 'True'], dtype='<U32')

In [7]:
# Matrices - Array con mas dimenciones: cuando existen mas dimencionesen un array se llaman MATRICES.
# Ejemplo creando Matrices.
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Comparando espacio en memoria de las listas vs los arrays.
import time

lista1 = range(1000000)
lista2 = range(1000000)
array1 = np.array(range(1000000))
array2 = np.array(range(1000000))

# tiempo de operación en listas
comienzo = time.time()
resultado = [x - y for x,y in zip(lista1, lista2)]
final = time.time()
print('Tiempo listas: ', final - comienzo)

# Tiempo de operación resta en arrays.
comienzo2 = time.time()
resultado = array1 - array2
final2 = time.time()
print('Tiempo Arrays: ', final2 - comienzo2)

Tiempo listas:  0.09757494926452637
Tiempo Arrays:  0.0038585662841796875


## Funciones universales.

- Se aplican a cada uno de los elementos del array.
- Cuando se usan 2 arrays se debe tener presente que ambos deben tener la misma longitud.

In [13]:
# Funciones aritmeticas.
# substract(): resta los elementos de dos arrays, elemento por elemento.
array1 = np.array([4, 89, 15])
array2 = np.array([6, 39, 10])
np.subtract(array1, array2)

array([-2, 50,  5])

In [14]:
# add(): suma los elementos de dos arrays 
array1 = np.array([4, 89, 15])
array2 = np.array([6, 39, 10])
np.add(array1, array2)

array([ 10, 128,  25])

In [15]:
# multiply(): multiplica los valores de dos arrays.
array1 = np.array([4, 89, 15])
array2 = np.array([6, 39, 10])
np.multiply(array1, array2)

array([  24, 3471,  150])

In [16]:
# divide(): divide los valores de 2 arrays
array1 = np.array([4, 89, 15])
array2 = np.array([6, 39, 10])
np.divide(array1, array2)

array([0.66666667, 2.28205128, 1.5       ])

In [17]:
# power(): devuelve la potencia del elelmento del primer array elevaro al elemento del segundo array
array1 = np.array([2, 4, 6])
array2 = np.array([2, 4, 6])
np.power(array1, array2)

array([    4,   256, 46656])

In [19]:
# sqrt(): Devuelve la raíz cuadrada de cada uno de los elementos
array1 = np.array([4, 89, 15])
np.sqrt(array1)

array([2.        , 9.43398113, 3.87298335])

In [20]:
# square(): devuelve el cuadrado de cada uno de los elementos de un array
array1 = np.array([4, 89, 15])
np.square(array1)

array([  16, 7921,  225])

In [26]:
# gcd(): devuelve el maximo comun divisor de los elementos de dos arrays
array1 = np.array([2, 4, 6])
array2 = np.array([22, 1, 66])
np.gcd(array1, array2)

array([2, 1, 6])

In [25]:
# lcm(): devuelve el minimo comun multiplo de los elementos de dos arrays.
array1 = np.array([2, 44, 6])
array2 = np.array([22, 4, 66])
np.lcm(array1, array2)

array([22, 44, 66])

## Funciones de comparación.

- Es un conjunto de funciones que permite comparar los elementos de dos arrays elemento por elemento.

In [28]:
# greater(): realiza la operación elem1 > elem2 por cada elemento de los arrays.
array1 = np.array([2, 4, 6])
array2 = np.array([8, 2, 12])
np.greater(array1, array2)

array([False,  True, False])

In [30]:
# greater_equal(): realiza la operación elem1 >= elem2 por cada elemento de los arrays.
array1 = np.array([2, 4, 6])
array2 = np.array([2, 2, 12])
np.greater_equal(array1, array2)

array([ True,  True, False])

In [31]:
# less(): realiza la operación elem1 < elem2 por cada elemento de los arrays.
array1 = np.array([2, 4, 6])
array2 = np.array([2, 2, 12])
np.less(array1, array2)

array([False, False,  True])

In [32]:
# less_equal(): realiza la operación elem1 <= elem2 por cada elemento de los arrays.
array1 = np.array([2, 4, 6])
array2 = np.array([2, 2, 12])
np.less_equal(array1, array2)

array([ True, False,  True])

In [33]:
# equal(): realiza la operación elem1 == elem2 por cada elemento de los arrays.
array1 = np.array([2, 4, 6])
array2 = np.array([2, 4, 12])
np.equal(array1, array2)

array([ True,  True, False])

In [34]:
# not_equal(): realiza la operación elem1 != elem2 por cada elemento de los arrays.
array1 = np.array([2, 4, 6])
array2 = np.array([2, 4, 12])
np.not_equal(array1, array2)

array([False, False,  True])

## Funciones Booleanas.

- Aplican a elemento por elemento de cada array sobre los que se realiza las operaciones.
- Deben contener valores booleanos.

In [35]:
# logical_and(): valida cada uno de los elementos.
array1 = np.array([True, False, True])
array2 = np.array([False, False, True])
np.logical_and(array1, array2)

array([False, False,  True])

In [36]:
# logical_or(): valida cada uno de los elementos.
array1 = np.array([True, False, True])
array2 = np.array([False, False, True])
np.logical_or(array1, array2)

array([ True, False,  True])

In [37]:
# logical_xor(): valida cada uno de los elementos.
array1 = np.array([True, False, True])
array2 = np.array([False, False, True])
np.logical_or(array1, array2)

array([ True, False,  True])

In [38]:
# logical_not(): valida cada uno de los elementos.
array1 = np.array([True, False, True])
np.logical_not(array1, array2)

array([False,  True, False])

## Funciones Estadisticas.

- Son funciones que pueden interactuar con los arrays.
- Sirven para realizar operaciones basadas en terminos estadisticos.

In [41]:
# amin(): devuelve el valor minimo de todos los elementosde un array, tambien aplica sobre matrices.
array = np.array([1,2,3,4,5,6,7,8,9,10])
print ("Minimo: Array", np.amin(array))

matriz = np.array([[1,2,3,4],[5,6,7,8,9,10]])
print ("Minimo Matriz: ", np.amin(matriz))

Minimo: Array 1
Minimo Matriz:  [1, 2, 3, 4]


/tmp/ipykernel_11/981180199.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  matriz = np.array([[1,2,3,4],[5,6,7,8,9,10]])


In [42]:
# amax(): devuelve el valor maximo de todos los elementosde un array, tambien aplica sobre matrices.
array = np.array([1,2,3,4,5,6,7,8,9,10])
print ("Maximo: Array", np.amax(array))

matriz = np.array([[1,2,3,4],[5,6,7,8,9,10]])
print ("Minimo Matriz: ", np.amax(matriz))

Maximo: Array 10
Minimo Matriz:  [5, 6, 7, 8, 9, 10]


/tmp/ipykernel_11/121281562.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  matriz = np.array([[1,2,3,4],[5,6,7,8,9,10]])


In [58]:
# percentil(): devuelve el valor sobre el que se encuentra un porcentaje de conjunto de observaciones 
# ordenados de mayor a menor
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Percentil 25: ", np.percentile(array, 25))

Percentil 25:  3.25


In [59]:
# median(): devuelve la mediana, el valor que separa el conjunto de observaciones ordenadas de mayor a menor / 2
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Mediana : ", np.median(array))

Mediana :  5.5


In [60]:
# mean (): Retorna la media, el valor de tendencia central de un conjunto de observaciones
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Media : ", np.mean(array))

Media :  5.5


In [61]:
# average(): Retorna la media ponderada de un conjunto de observaciones 
pesos = np.array([0.2,0.05,0.05,0.3,0.0,0.1,0.05,0.05,0.1,0.1])
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Media Ponderada: ", np.average(array, weights=pesos))

Media Ponderada:  4.9


In [62]:
# std(): Retorna la desviación estándar de un conjunto de observaciones.
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Desviación estandar: ", np.std(array))

Desviación estandar:  2.8722813232690143


In [63]:
# var(): Retorna la varianza de un conjunto de operaciones.
array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Varianza: ", np.var(array))

Varianza:  8.25


## Programación orientada a objetos.

- Un objeto es una abstraccion de los datos con ciertas caracteristicas.
- Los objetos tienen un comportamiento, una identidad.
- Los objetos tienen un identificador para diferenciar entre los mismos.

In [12]:
# En una clase se define que operaciones se puede hacer y que caracteristicas tienen.
# Los atributos son un conjunto de valores que almacenan un valor, estructura, caracteristica.
# Clase Libro.
class Libro:
    titulo = "Don quijote de la mancha"
    autor = "Miguel de Cervantes"
    isbn = "0987-7489"
    editorial = "Una editorial"
    paginas = 987
    edicion = 34
    
# Creando un constructor.
    def __init__(self, titulo, autor, isbn, editorial, paginas, edicion):
        self.titulo  = titulo
        self.autor = autor
        self.isbn = isbn
        self.editorial = editorial
        self.paginas = paginas
        self.edicion = edicion
    
    def modificacion(self, sumaEdicion):
        self.edicion += sumaEdicion

In [14]:
# Creando un objeto de la clase libro
miLibro = Libro("El principito", "Anonimo", "0658-7859", "Mi editorial", 25, 1)

In [15]:
# Accediendo a los objetos de la clase Libro con el objeto miLibro
miLibro.titulo

'El principito'

In [16]:
# Accediendo a los objetos de la clase Libro con el objeto miLibro
miLibro.isbn

'0658-7859'

In [17]:
miLibro.edicion

1

In [18]:
miLibro.modificacion(5)

In [19]:
miLibro.edicion

6

In [41]:
class Persona:
    """
    Clase persona
    
    Esta clase cuenta con cuatro atributos y un metodo
    """
    def __init__(self, nombre, fechaNacimiento, domicilio):
        self.nombre = nombre
        self.fechaNacimiento = fechaNacimiento
        self.domicilio = domicilio

    def cambiarDomicilio(self, nuevoDomicilio):
        self.domicilio = nuevoDomicilio

In [42]:
class Profesor (Persona):
    def __init__(self, nombre, fechaNacimiento, domicilio, identificacionProfesor):
        Persona.__init__(self, nombre, fechaNacimiento, domicilio)
        self.identificacionProfesor = identificacionProfesor
    
    def modificaIdentificacion (self, nuevaIdentificacion):
        self.identificacion = nuevaIdentificacion

In [43]:
class Alumno(Persona):
    def __init__(self, nombre, fechaNacimiento, domicilio, calificacion):
        Persona.__init__(self, nombre, fechaNacimiento, domicilio)
        self.calificacion = calificacion
    
    def calificar(self,nota):
        self.calificacion = nota

In [44]:
alumno = Alumno("Oscar", "30/08/1990", "calle inventada", 0)
profesor = Profesor("pepe", "12/12/1975", "calle inventada", "123456")

In [45]:
alumno.domicilio

'calle inventada'

In [46]:
profesor.nombre

'pepe'

In [47]:
alumno.cambiarDomicilio("Inventado 789")

In [48]:
alumno.domicilio

'Inventado 789'

In [49]:
alumno.calificar(7)

In [50]:
alumno.calificacion

7

In [51]:
help(Persona)

Help on class Persona in module __main__:

class Persona(builtins.object)
 |  Persona(nombre, fechaNacimiento, domicilio)
 |  
 |  Clase persona
 |  
 |  Esta clase cuenta con cuatro atributos y un metodo
 |  
 |  Methods defined here:
 |  
 |  __init__(self, nombre, fechaNacimiento, domicilio)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  cambiarDomicilio(self, nuevoDomicilio)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



## Exoresiones Regulares.

- Permiten encontrar patrones de expresiones regulares.
- Se usa con la libreria re

In [1]:
# Importando libreria
import re

In [3]:
mensaje = "Esto es un mensaje de ejemplo del curso de python"

match = re.search("curso", mensaje)

In [4]:
match.end()

39

In [5]:
match2 = re.match("Esto", mensaje)

In [6]:
match2.end()

4

In [9]:
mensajeSinEspacios = re.split(" ", mensaje)

In [10]:
mensajeSinEspacios

['Esto',
 'es',
 'un',
 'mensaje',
 'de',
 'ejemplo',
 'del',
 'curso',
 'de',
 'python']

In [11]:
patron = re.findall("de", mensaje)

In [12]:
patron

['de', 'de', 'de']

In [15]:
texto = "Un texto es una composición de signos codificados en un sistema de escritura que forma una unidad de sentido.\
También es una composición de caracteres imprimibles (con grafema) generados por un algoritmo de cifrado que,\
aunque no tienen sentido para cualquier persona, sí puede ser descifrado por su destinatario original. \
En otras palabras, un texto es un entramado de signos con una intención comunicativa que adquiere sentido en\
determinado contexto."

In [18]:
patron = "(se\w+)\s\w+"

In [19]:
re.findall(patron, texto)

['sentido', 'ser', 'sentido']

In [20]:
# Incluyendo metacaracteres.
re.findall("es|ser", texto)

['es', 'es', 'es', 'es', 'es', 'ser', 'es', 'es', 'es']

In [21]:
ejemplo = "1 22 333 4444"

In [22]:
re.findall("\d?\s", ejemplo)

['1 ', '2 ', '3 ']